image: registry.gitlab.com/marsoner/docker-for-test-coverage:latest

stages:
- test
- deploy

consistency:
  stage: test
  script:
    - python3 consistency_check.py
  artifacts:
    name: pages
    paths:
    - paths.svg
  
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r paths.svg .public
    - mv .public public
  artifacts:
    name: pages
    paths:
    - public
  only:
    - master  

publish:
  stage: deploy
  before_script:
    - echo $FIREBASE_KEY | PASSPHRASE=$FIREBASE_KEY gpg --batch --pinentry-mode loopback --command-fd 0 -r test@example.com -d hundetage.gpg > hundetage.key
  script:
    - python3 firebase_upload.py