image: python:3.7

stages:
- test

consistency:
  stage: test
  script:
    - pip install anybadge
    - python consistency_check.py
    - mv  paths.svg public/paths.svg
  artifacts:
    paths:
    - public/paths.svg