image: registry.gitlab.com/marsoner/docker-for-test-coverage:latest

stages:
- test
- deploy

consistency:
  stage: test
  script:
    - python3 consistency_check.py
  artifacts:
    name: pages
    paths:
    - paths.svg
  
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r paths.svg .public
    - mv .public public
  artifacts:
    name: pages
    paths:
    - public
  only:
    - master  

publish:
  stage: deploy
  before_script:
    - echo $FIREBASE_KEY
    - cat $FIREBASE_KEY | gpg2 --output hundetage.key --decrypt --passphrase-fd 0 hundetage.gpg
  script:
    - python3 firebase_upload.py