image: python:3.7

stages:
- test
- deploy

consistency:
  stage: test
  script:
    - pip install anybadge
    - python consistency_check.py
  artifacts:
    name: pages
    paths:
    - paths.svg
    
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r *.svg .public
    - mv .public public
  artifacts:
    name: pages
    paths:
    - public
  only:
    - master  
