image: python:3.7

stages:
- test
- deploy

consistency:
  stage: test
  script:
    - pip install anybadge
    - python consistency_check.py
  artifacts:
    name: pages
    paths:
    - paths.svg
    
pages:
  stage: deploy
  artifacts:
    name: pages
    paths:
    - paths.svg
  only:
  - master
